### ISSUE TITLE
build.lua error

### ISSUE THREAD

**Issue by Klonan** [DaveMcW/factorio-movie-maker#1]
I get an error when i try to run the lua script:
`ls: cannot access 'images/*.bmp': No such file or directory
`

seems like something is going wrong in here:
line 19
`	if (unix) then
		pfile = io.popen('ls "'..dir..'/'..ext..'"')
		for filename in pfile:lines() do
			table.insert(files, filename)
		end
	else`

**Comment by ghost** [comment]
Not sure but fixed it by removing the "

->
('ls '..dir..'/'..ext..'')
